import '@/styles/globals.css'

import { type Metadata } from 'next'
import { Toaster } from '@/components/ui/toaster'
import { TRPCReactProvider } from '@/trpc/react'
import { GeistSans } from 'geist/font/sans'
import { SessionProvider } from 'next-auth/react'

import { HackathonBanner } from './_components/hackathon-banner'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <HackathonBanner />
        <SessionProvider>
          <TRPCReactProvider>
            {children}
            <Toaster />
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
