CREATE TABLE "hoodgoods_business" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hoodgoods_business_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"owner_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hoodgoods_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hoodgoods_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hoodgoods_tag_business" (
	"tag_id" integer NOT NULL,
	"business_id" integer NOT NULL,
	CONSTRAINT "hoodgoods_tag_business_tag_id_business_id_pk" PRIMARY KEY("tag_id","business_id")
);
--> statement-breakpoint
CREATE TABLE "hoodgoods_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"phone" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "hoodgoods_user_phone_unique" UNIQUE("phone")
);
--> statement-breakpoint
ALTER TABLE "hoodgoods_business" ADD CONSTRAINT "hoodgoods_business_owner_id_hoodgoods_user_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."hoodgoods_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hoodgoods_tag_business" ADD CONSTRAINT "hoodgoods_tag_business_tag_id_hoodgoods_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."hoodgoods_tag"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hoodgoods_tag_business" ADD CONSTRAINT "hoodgoods_tag_business_business_id_hoodgoods_business_id_fk" FOREIGN KEY ("business_id") REFERENCES "public"."hoodgoods_business"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "owner_id_idx" ON "hoodgoods_business" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "name_idx" ON "hoodgoods_business" USING btree ("name");